media/gallery/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'gallery'

urlpatterns = [
    path('',
         views.gallery_hp,
         name='homepage'),
    path('video',
         views.video_list,
         name='video_list'),

    path('audio',
         views.audio_list,
         name='audio_list'),

    path('image',
         views.image_list,
         name='image_list'),    # caching view 15 min

    path('<model_name>/create/',
         views.GalleryCreateUpdateView.as_view(),
         name='gallery_create'),

    # path('<model_name>/<int:id>/',
    #      views.GalleryCreateUpdateView.as_view(),
    #      name='gallery_update'),
]

media/media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from gallery.views import gallery_hp


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('', gallery_hp, name='hp')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

media/gallery/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.validators import RegexValidator
from django.db.models.signals import post_delete
from django.dispatch import receiver


class Content(models.Model):
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in': (
                                        'video',
                                        'image',
                                        'audio')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ['-object_id']


class ItemBase(models.Model):
    alphanumeric = RegexValidator(r'^[0-9a-zA-Z]+$', 'Only alphanumeric characters, are allowed.')

    title = models.CharField(max_length=250, validators=[alphanumeric])
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class Audio(ItemBase):
    file = models.FileField(upload_to='audios', blank=False)


class Image(ItemBase):
    file = models.FileField(upload_to='images', blank=False)


class Video(ItemBase):
    # url = RegexValidator(r'%^(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@|\d{1,3}(?:\.\d{1,3}){3}|(?:(?:[a-z\d\x{00a1}-\x{ffff}]+-?)*[a-z\d\x{00a1}-\x{ffff}]+)(?:\.(?:[a-z\d\x{00a1}-\x{ffff}]+-?)*[a-z\d\x{00a1}-\x{ffff}]+)*(?:\.[a-z\x{00a1}-\x{ffff}]{2,6}))(?::\d+)?(?:[^\s]*)?$%', 'URL not allowed.')
    # url = models.URLField(blank=True, validators=[url])
    file = models.FileField(upload_to='videos', blank=False)


''' Credits : Michael Nelson, Mattias Omisore '''
""" Whenever ANY model is deleted, if it has a file field on it, delete the associated file too"""


@receiver(post_delete)
def delete_files_when_row_deleted_from_db(sender, instance, **kwargs):
    for field in sender._meta.concrete_fields:
        if isinstance(field, models.FileField):
            instance_file_field = getattr(instance, field.name)
            delete_file_if_unused(sender, instance, field, instance_file_field)


""" Delete the file if something else get uploaded in its place"""


# @receiver(pre_save)
# def delete_files_when_file_changed(sender, instance, **kwargs):
#     # Don't run on initial save
#     if not instance.pk:
#         return
#     for field in sender._meta.concrete_fields:
#         if isinstance(field, models.FileField):
#             # its got a file field. Let's see if it changed
#             try:
#                 instance_in_db = sender.objects.get(pk=instance.pk)
#             except sender.DoesNotExist:
#                 # We are probably in a transaction and the PK is just temporary
#                 # Don't worry about deleting attachments if they aren't actually saved yet.
#                 return
#             instance_in_db_file_field = getattr(instance_in_db, field.name)
#             instance_file_field = getattr(instance, field.name)
#             if instance_in_db_file_field.name != instance_file_field.name:
#                 delete_file_if_unused(sender, instance, field, instance_in_db_file_field)


""" Only delete the file if no other instances of that model are using it"""


def delete_file_if_unused(model, instance, field, instance_file_field):
    dynamic_field = {}
    dynamic_field[field.name] = instance_file_field.name
    other_refs_exist = model.objects.filter(**dynamic_field).exclude(pk=instance.pk).exists()
    if not other_refs_exist:
        instance_file_field.delete(False)


''' end credits '''

media/gallery/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic.base import TemplateResponseMixin, View
from django.apps import apps
from django.forms.models import modelform_factory
from .models import Video, Audio, Image, Content
from .common import get_file_extension, delete_cache
from django.core.cache import cache
from var_dump import var_dump


def gallery_hp(request):
    return render(request,
                  'gallery/homepage.html',
                  )


# low-level cache API
def audio_list(request):
    audios = cache.get('audios')
    if not audios:
        audios = Audio.objects.all()
        cache.set('audios', audios)
    return render(request,
                  'gallery/audio/list.html',
                  {'audios': audios})


# low-level cache API
def image_list(request):
    images = cache.get('images')
    if not images:
        images = Image.objects.all()
        cache.set('images', images)
    return render(request,
                  'gallery/image/list.html',
                  {'images': images})


# low-level cache API
def video_list(request):
    videos = cache.get('videos')
    if not videos:
        videos = Video.objects.all()
        cache.set('videos', videos)
    return render(request,
                  'gallery/video/list.html',
                  {'videos': videos})


class GalleryCreateUpdateView(TemplateResponseMixin, View):
    model = None
    obj = None
    template_name = 'gallery/media_form.html'

    def get_model(self, model_name):
        if model_name in ['video', 'image', 'audio']:
            return apps.get_model(app_label='gallery',
                                  model_name=model_name)
        return None

    def get_form(self, model, *args, **kwargs):
        form = modelform_factory(model, exclude=['created', 'updated'])

        return form(*args, **kwargs)

    def dispatch(self, request, model_name, id=None):
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model,
                                         id=id)
        return super().dispatch(request, model_name, id)

    def get(self, request, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form,
                                        'object': self.obj})

    def post(self, request, model_name, id=None):
        form = self.get_form(self.model,
                             instance=self.obj,
                             data=request.POST,
                             files=request.FILES)

        if form.is_valid():
            obj = form.save()
            fe = get_file_extension(model_name, form)
            # var_dump(fe)
            if fe.get('name') not in fe.get('list_allowed'):
                obj.delete()
                messages.error(request, 'File extension not allowed')
                return redirect(reverse('gallery:gallery_create', args=[model_name]))

            if not id:
                # new content
                Content.objects.create(item=obj)
                delete_cache(model_name)
                return redirect('gallery:homepage')

        return self.render_to_response({'form': form, 'object': self.obj})

media/gallery/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/unitegallery/css/unite-gallery.css' %}" rel="stylesheet">
        <link href="{% static 'css/unitegallery/themes/default/ug-theme-default.css' %}" rel="stylesheet">
        <link href="{% static 'css/site.css' %}" rel="stylesheet">

    </head>
    <body>
        {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li class="{{ message.tags }}">
                  {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
              {% endfor %}
            </ul>

        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <script type="text/javascript" src="{% static 'js/jquery/jquery-1.11.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/unitegallery/js/unitegallery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/unitegallery/themes/default/ug-theme-default.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/site/video_audio_gallery.js' %}"></script>
    </body>
</html>

media/gallery/templates/gallery/audio/list.html
{% extends "base.html" %}
{% block title %}Audios{% endblock %}

{% block content %}
    <div id="content">
        <div id="video-gallery">
            {% for audio in audios %}
                <div data-type="html5video"
                     src="/static/css/images/play_video.png"
                     data-image="/static/css/images/play_video.png"
                     data-videomp4="{{ MEDIA_URL }}{{audio.file}}"
                     data-title="{{audio.title}}"
                     data-description="{{audio.title}}">
                </div>
            {% endfor %}
        </div>
        <ul class="buttons">
            <li><a href="{% url 'gallery:gallery_create' 'audio' %}">Upload an audio</a></li>
            <li class="button"> <a href="{% url 'gallery:homepage' %}">Home</a></li>
        </ul>
    </div>
{% endblock %}

media/gallery/templates/gallery/homepage.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}

{% block content %}
    <div id="content">
        <ul class="buttons">
            <li><a href="{% url 'gallery:video_list' %}">Video Gallery</a></li>
            <li><a href="{% url 'gallery:audio_list' %}">Audio Gallery</a></li>
            <li><a href="{% url 'gallery:image_list' %}">Image Gallery</a></li>
        </ul>
    </div>
{% endblock %}

media/gallery/templates/gallery/image/list.html
{% extends "base.html" %}
{% block title %}Images{% endblock %}

{% block content %}
    <div id="content">
        <div id="image-gallery" style="display:none">
            {% for image in images %}
                <img alt="{{image.title}}" src="{{ MEDIA_URL }}{{image.file}}"
                data-image="{{ MEDIA_URL }}{{image.file}}"
                data-description="{{ MEDIA_URL }}{{image.file}}">
            {% endfor%}
        </div>
       <ul class="buttons">
            <li><a href="{% url 'gallery:gallery_create' 'image' %}">Upload an image</a></li>
            <li class="button"> <a href="{% url 'gallery:homepage' %}">Home</a></li>
        </ul>
    </div>
{% endblock %}

media/gallery/templates/gallery/media_form.html
{% extends "base.html" %}

{% block title %}
    Add new media
{% endblock %}

{% block content %}
  <h1>
      Add new media
  </h1>
  <div class="module">
    <form id="#myForm" method="post" enctype="multipart/form-data">
      {{ form.as_table }}
      {% csrf_token %}
      <p><input type="submit" value="Save content"></p>
    </form>
  </div>
{% endblock %}

media/gallery/templates/gallery/video/list.html
{% extends "base.html" %}
{% load cache %}
{% block title %}Videos{% endblock %}

{% block content %}
    <div id="content">
        <div id="video-gallery">
                {% for video in videos %}
                    <div data-type="html5video"
                         src="/static/css/images/play_video.png"
                         data-image="/static/css/images/play_video.png"
                         data-videomp4="{{ MEDIA_URL }}{{video.file}}"
                         data-title="{{video.title}}"
                         data-description="{{video.title}}">
                    </div>
                {% endfor %}
        </div>
        <ul class="buttons">
            <li><a href="{% url 'gallery:gallery_create' 'video' %}">Upload an video</a></li>
            <li class="button"> <a href="{% url 'gallery:homepage' %}">Home</a></li>
        </ul>
    </div>
{% endblock %}